<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net6.0</TargetFrameworks>

    <ApplicationIcon>..\NzbDrone.Host\Readarr.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="!$(RuntimeIdentifier.StartsWith('win'))">
    <AssemblyName>Inkarr</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Host\Inkarr.Host.csproj" />
  </ItemGroup>
</Project>
