<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net6.0-windows</TargetFrameworks>
    <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0-windows'">
    <PackageReference Include="System.Security.Principal.Windows" />
  </ItemGroup>
</Project>
