<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mono.Posix.NETStandard" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Common.Test\Inkarr.Common.Test.csproj" />
    <ProjectReference Include="..\NzbDrone.Test.Common\Inkarr.Test.Common.csproj" />
    <ProjectReference Include="..\NzbDrone.Mono\Inkarr.Mono.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Files\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
