<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0-windows</TargetFrameworks>
    <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NLog" />
    <PackageReference Include="System.IO.FileSystem.AccessControl" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Common\Inkarr.Common.csproj" />
  </ItemGroup>
</Project>
