// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentContainer': string;
  'errorMessage': string;
  'filterIcon': string;
  'innerContentBody': string;
  'metadataMessage': string;
  'selectedTab': string;
  'tab': string;
  'tabContent': string;
  'tabList': string;
  'volumeNavigationButton': string;
  'volumeNavigationButtons': string;
  'volumeUpButton': string;
}
export const cssExports: CssExports;
export default cssExports;
