<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Common.Test\Inkarr.Common.Test.csproj" />
    <ProjectReference Include="..\NzbDrone.Test.Common\Inkarr.Test.Common.csproj" />
    <ProjectReference Include="..\NzbDrone.Windows\Inkarr.Windows.csproj" />
  </ItemGroup>
</Project>
