<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="DryIoc.dll" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    <PackageReference Include="DryIoc.Microsoft.DependencyInjection" />
    <PackageReference Include="System.Text.Encoding.CodePages" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Inkarr.Api.V1\Inkarr.Api.V1.csproj" />
    <ProjectReference Include="..\NzbDrone.Common\Inkarr.Common.csproj" />
    <ProjectReference Include="..\NzbDrone.Core\Inkarr.Core.csproj" />
    <ProjectReference Include="..\NzbDrone.SignalR\Inkarr.SignalR.csproj" />
    <ProjectReference Include="..\Inkarr.Http\Inkarr.Http.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Interop.NetFwTypeLib">
      <HintPath>..\Libraries\Interop.NetFwTypeLib.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
  </ItemGroup>
</Project>
